version: "2"

linters:
  enable:
    - unconvert
    - goconst
    - misspell
    - unparam
    - nakedret
    - prealloc
    - revive
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: redundant-build-tag
  exclusions:
    rules:
      - path: '(.+)\.go$'
        text: G104

formatters:
  enable:
    - gofmt

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
